FROM public.ecr.aws/lambda/provided:al2023@sha256:ba393740482b4748214642e38f35eec40591556276cdfd9e9f45fd194348fb4f

RUN dnf install -y unzip wget && \
    wget "https://github.com/buildkite/buildkite-agent-metrics/releases/latest/download/handler.zip" && \
    unzip handler.zip && rm -f handler.zip

ENTRYPOINT ["./bootstrap"]
