FROM public.ecr.aws/lambda/provided:al2023@sha256:2a8ac0e2216f7636e9de68fe5e85f015a3518d42a9a35942d6734199a8d3b2bd

RUN dnf install -y unzip wget && \
    wget "https://github.com/buildkite/buildkite-agent-metrics/releases/latest/download/handler.zip" && \
    unzip handler.zip && rm -f handler.zip

ENTRYPOINT ["./bootstrap"]
