FROM public.ecr.aws/docker/library/alpine:3.22.0@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715
ARG TARGETARCH
RUN apk update && apk add --no-cache curl ca-certificates
COPY dist/buildkite-agent-metrics-linux-${TARGETARCH} ./buildkite-agent-metrics
RUN chmod +x ./buildkite-agent-metrics
EXPOSE 8080 8125
ENTRYPOINT ["./buildkite-agent-metrics"]
