FROM public.ecr.aws/docker/library/alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
ARG TARGETARCH
RUN apk update && apk add --no-cache curl ca-certificates
COPY dist/buildkite-agent-metrics-linux-${TARGETARCH} ./buildkite-agent-metrics
RUN chmod +x ./buildkite-agent-metrics
EXPOSE 8080 8125
ENTRYPOINT ["./buildkite-agent-metrics"]
