services:
  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ../:/work:cached
      - ~/gocache:/gocache
      - ~/gomodcache:/gomodcache
    working_dir: /work
    environment:
      - GOCACHE=/gocache
      - GOMODCACHE=/gomodcache

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ../:/work:cached
      - ~/gocache:/gocache
      - ~/gomodcache:/gomodcache
    working_dir: /work
    environment:
      - GOCACHE=/gocache
      - GOMODCACHE=/gomodcache

  release:
    build:
      context: .
      dockerfile: Dockerfile.release
    volumes:
      - ../:/work:cached
    working_dir: /work
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_AGENT_TAGS=queue=default
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_PATH=/buildkite
      - BUILDKITE_JOB_ID
      - BUILDKITE_TAG
      - GITHUB_RELEASE_ACCESS_TOKEN
      - RELEASE_DRY_RUN
