env:
  SEGMENT_CONTEXTS: 'aws-credentials,ecr'

steps:
  - name: ":hammer_and_wrench:"
    plugins:
      - docker#v3.2.0:
          image: "golang:1.11"
          command: ["go", "test", "-v", "-race", "."]
          environment:
            - GO111MODULE=on

  - label: ':hammer: Build'
    commands:
      - "docker build -t ${TREB_IMAGE_TAG} ."
      - "docker tag ${TREB_IMAGE_TAG} ${TREB_SHORT_IMAGE_TAG}"
      - "docker push ${TREB_IMAGE_TAG}"

  - label: ':happo: Publish'
    plugins:
      - ssh://git@github.com/segmentio/treb-publish-buildkite-plugin#v0.2.0:
          configs:
            - .run/buildkite-agent-metrics.yml
