steps:
  - name: ":test_tube: Test"
    key: test
    command: go test -v -race .
    plugins:
      - docker#v5.9.0:
          image: golang:1.21

  - group: ":hammer_and_wrench: Binary builds"
    steps:
    - name: ":{{matrix.os}}: Build {{matrix.os}} {{matrix.arch}} binary"
      command: .buildkite/steps/build-binary.sh {{matrix.os}} {{matrix.arch}}
      key: build-binary
      depends_on:
        - test
      plugins:
        - docker#v5.9.0:
            image: golang:1.21
            mount-buildkite-agent: true
      matrix:
        setup:
          os:
            - darwin
            - linux
            - windows
          arch:
            - amd64
            - arm64

  - name: ":lambda: Build Lambda"
    key: build-lambda
    command: .buildkite/steps/build-lambda.sh

  - name: ":s3: Upload to S3"
    key: upload-to-s3
    depends_on:
      - test
      - build-lambda
    command: ".buildkite/steps/upload-to-s3.sh"
    branches: master
    agents:
      queue: "elastic-runners"
    concurrency: 1
    concurrency_group: "release_buildkite_metrics_s3"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-buildkite-agent-metrics

  - name: ":pipeline:"
    key: upload-release-steps
    depends_on:
      - build-binary
      - upload-to-s3
    command: .buildkite/steps/upload-release-steps.sh
