steps:
  - name: ":hammer_and_wrench:"
    plugins:
      - docker#v2.0.0:
          image: "golang:1.16"
          command: ["go", "test", "-v", "-race", "."]
          environment:
            - GO111MODULE=on

  - wait
  - name: ":golang: :pipeline:"
    plugins:
      - golang-cross-compile#v1.3.0:
          build: main.go
          import: github.com/buildkite/buildkite-agent-metrics
          targets:
            - version: "1.16"
              goos: linux
              goarch: amd64
              gomodule: "on"
            - version: "1.16"
              goos: linux
              goarch: arm64
              gomodule: "on"
            - version: "1.16"
              goos: windows
              goarch: amd64
              gomodule: "on"
            - version: "1.16"
              goos: darwin
              goarch: amd64
              gomodule: "on"
            - version: "1.16"
              goos: darwin
              goarch: arm64
              gomodule: "on"

  - name: "Upload Docker Image"
    command: buildkite-agent pipeline upload .buildkite/pipeline.gcr.yml
