env:
  RELEASE_DRY_RUN: false

steps:
  - name: ":test_tube: Test"
    key: test
    command: go test -v -race ./...
    plugins:
      - docker-compose#v5.5.0:
          config: .buildkite/docker-compose.yaml
          cli-version: 2
          run: test

  - group: ":hammer_and_wrench: Binary builds"
    steps:
      - name: ":{{matrix.os}}: Build {{matrix.os}} {{matrix.arch}} binary"
        command: .buildkite/steps/build-binary.sh {{matrix.os}} {{matrix.arch}}
        key: build-binary
        depends_on:
          - test
        plugins:
          - docker-compose#v5.5.0:
              config: .buildkite/docker-compose.yaml
              cli-version: 2
              run: build
        matrix:
          setup:
            os:
              - darwin
              - linux
              - windows
            arch:
              - amd64
              - arm64
        artifact_paths:
          - ./dist/*

  - name: ":lambda: Build Lambda"
    key: build-lambda
    depends_on:
      - test
    command: .buildkite/steps/build-lambda.sh
    plugins:
      - docker-compose#v5.5.0:
          config: .buildkite/docker-compose.yaml
          cli-version: 2
          run: build
    artifact_paths:
      - ./dist/*

  - name: ":s3: Upload to S3"
    key: upload-to-s3
    depends_on:
      - test
      - build-lambda
    command: ".buildkite/steps/upload-to-s3.sh"
    branches: master
    agents:
      queue: "elastic-runners"
    concurrency: 1
    concurrency_group: "release_buildkite_metrics_s3"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::172840064832:role/pipeline-buildkite-buildkite-agent-metrics

  - if: build.env("RELEASE_DRY_RUN") == "true" || build.env("BUILDKITE_TAG") =~ /^v\d+\.\d+\.\d+$$/
    block: ":rocket: Release ${BUILDKITE_TAG:-UNTAGGED}?"
    key: block-release
    depends_on:
      - build-binary
      - upload-to-s3

  - if: build.env("RELEASE_DRY_RUN") == "true" || build.env("BUILDKITE_TAG") =~ /^v\d+\.\d+\.\d+$$/
    name: ":rocket: Release"
    key: trigger-release
    trigger: "buildkite-agent-metrics-release"
    async: false
    depends_on:
      - block-release
    build:
      message: "Release for ${BUILDKITE_TAG:-UNTAGGED}, build ${BUILDKITE_BUILD_NUMBER}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        RELEASE_VERSION_TAG: "${BUILDKITE_TAG:-UNTAGGED}"
        RELEASE_DRY_RUN: "${RELEASE_DRY_RUN:-false}"
