// Code generated by MockGen. DO NOT EDIT.
// Source: secretsmanager.go
//
// Generated by this command:
//
//	mockgen -source secretsmanager.go -mock_names SecretsManagerClient=SecretsManagerClient -package mock -destination mock/secretsmanager_client.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	secretsmanager "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	gomock "go.uber.org/mock/gomock"
)

// SecretsManagerClient is a mock of SecretsManagerClient interface.
type SecretsManagerClient struct {
	ctrl     *gomock.Controller
	recorder *SecretsManagerClientMockRecorder
	isgomock struct{}
}

// SecretsManagerClientMockRecorder is the mock recorder for SecretsManagerClient.
type SecretsManagerClientMockRecorder struct {
	mock *SecretsManagerClient
}

// NewSecretsManagerClient creates a new mock instance.
func NewSecretsManagerClient(ctrl *gomock.Controller) *SecretsManagerClient {
	mock := &SecretsManagerClient{ctrl: ctrl}
	mock.recorder = &SecretsManagerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *SecretsManagerClient) EXPECT() *SecretsManagerClientMockRecorder {
	return m.recorder
}

// GetSecretValue mocks base method.
func (m *SecretsManagerClient) GetSecretValue(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSecretValue", varargs...)
	ret0, _ := ret[0].(*secretsmanager.GetSecretValueOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretValue indicates an expected call of GetSecretValue.
func (mr *SecretsManagerClientMockRecorder) GetSecretValue(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretValue", reflect.TypeOf((*SecretsManagerClient)(nil).GetSecretValue), varargs...)
}
