// Code generated by MockGen. DO NOT EDIT.
// Source: ssm.go
//
// Generated by this command:
//
//	mockgen -source ssm.go -mock_names SSMClient=SSMClient -package mock -destination mock/ssm_client.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"
	gomock "go.uber.org/mock/gomock"
)

// SSMClient is a mock of SSMClient interface.
type SSMClient struct {
	ctrl     *gomock.Controller
	recorder *SSMClientMockRecorder
	isgomock struct{}
}

// SSMClientMockRecorder is the mock recorder for SSMClient.
type SSMClientMockRecorder struct {
	mock *SSMClient
}

// NewSSMClient creates a new mock instance.
func NewSSMClient(ctrl *gomock.Controller) *SSMClient {
	mock := &SSMClient{ctrl: ctrl}
	mock.recorder = &SSMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *SSMClient) EXPECT() *SSMClientMockRecorder {
	return m.recorder
}

// GetParameter mocks base method.
func (m *SSMClient) GetParameter(ctx context.Context, params *ssm.GetParameterInput, optFns ...func(*ssm.Options)) (*ssm.GetParameterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetParameter", varargs...)
	ret0, _ := ret[0].(*ssm.GetParameterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParameter indicates an expected call of GetParameter.
func (mr *SSMClientMockRecorder) GetParameter(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParameter", reflect.TypeOf((*SSMClient)(nil).GetParameter), varargs...)
}
