{
 "title": "Buildkite Agent Metrics",
 "description": "Displays Prometheus metrics collected from the Buildkite Agent Metrics exporter.",
 "tags": [
  "buildkite",
  "ci/cd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "CLUSTER", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "QUEUE",
    "label": "Queue",
    "query": {
     "query": "label_values({cluster=\"$CLUSTER\"},queue)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$CLUSTER cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "CLUSTER" },
  {
   "title": "Total agents",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "buildkite_total_total_agent_count{cluster=\"$CLUSTER\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Busy agents",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(buildkite_total_busy_agent_count{cluster=\"$CLUSTER\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle agents",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(buildkite_total_idle_agent_count{cluster=\"$CLUSTER\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduled jobs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(buildkite_total_scheduled_jobs_count{cluster=\"$CLUSTER\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting jobs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(buildkite_total_waiting_jobs_count{cluster=\"$CLUSTER\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running jobs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(buildkite_total_running_jobs_count{cluster=\"$CLUSTER\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unfinished jobs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(buildkite_total_unfinished_jobs_count{cluster=\"$CLUSTER\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agents running by queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(queue) (buildkite_queues_total_agent_count{cluster=\"$CLUSTER\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total jobs by queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (queue) ({__name__=~\"buildkite_queues_(scheduled|waiting|running)_jobs_count\", cluster=\"$CLUSTER\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$QUEUE queue metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "QUEUE" },
  {
   "title": "Agents by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(buildkite_queues_busy_agent_count{queue=\"$QUEUE\"})",
     "legendFormat": "Busy"
    },
    {
     "expr": "sum(buildkite_queues_idle_agent_count{queue=\"$QUEUE\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Jobs by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum (buildkite_queues_waiting_jobs_count{queue=\"$QUEUE\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum (buildkite_queues_scheduled_jobs_count{queue=\"$QUEUE\"})",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum (buildkite_queues_running_jobs_count{queue=\"$QUEUE\"})",
     "legendFormat": "Running"
    }
   ]
  }
 ]
}